parameters:
    env(MESSENGER_TRANSPORT_DSN): 'doctrine://default'

framework:
    messenger:
        transports:
            doctrine: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            App\Entity\Book: doctrine
